version: '3.8'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: backend_service
        command: /bin/sh -c 'php artisan migrate && php artisan storage:link && php artisan serve  --host=0.0.0.0'
        volumes:
            - .:/ledja
        ports:
            - 8000:8000
        depends_on: 
            - db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.entrypoints=web, web-secure"
            - "traefik.http.routers.backend.rule=Host(`api.direktory.biz`)"
            - "traefik.http.routers.backend.tls=true"
            

    frontend:
        build: ../ledja-frontend
        container_name: frontend_service
        # volumes:
        #     - .:/ledja-frontend
        command: /bin/sh -c 'npm run build && npm run start'
        env_file:
            - ../ledja-frontend/.env
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.entrypoints=web, web-secure"
            - "traefik.http.routers.frontend.rule=Host(`direktory.biz`)"
            - "traefik.http.routers.frontend.tls=true"
      
    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306     

    traefik:
        image: traefik:latest
        container_name: traefik
        command:
        - --entrypoints.web.address=:80
        - --entrypoints.web-secure.address=:443
        - --entrypoints.web.http.redirections.entryPoint.to=web-secure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entrypoints.web.http.redirections.entrypoint.permanent=true
        - --providers.docker=true
        - --providers.file.directory=/configuration/
        - --providers.file.watch=true

        # restart: on-failure
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "/etc/letsencrypt:/etc/letsencrypt"
        # Add all our tls certificates here
        # Api service tls
        - "/etc/letsencrypt/live/api.direktory.biz/fullchain.pem:/certs/backend/fullchain.pem"
        - "/etc/letsencrypt/live/api.direktory.biz/privkey.pem:/certs/backend/privkey.pem"
        # Frontend service tls
        - "/etc/letsencrypt/live/direktory.biz/fullchain.pem:/certs/frontend/fullchain.pem"
        - "/etc/letsencrypt/live/direktory.biz/privkey.pem:/certs/frontend/privkey.pem"


        - "/home/talimwakesi/srv/ledja/configuration:/configuration/"

volumes:
    dbdata:
